name = "AlgorithmsCollection"
uuid = "9ff941b3-d743-4c60-9dd5-2748db76006b"
authors = ["Julia-Algorithms <Julia-Algorithms@gmail.com>", "Anselm Hahn <Anselm.Hahn@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
